# Generated by Django 4.1.13 on 2024-12-18 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfitEase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='date_sold',
        ),
        migrations.AddField(
            model_name='sales',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=2, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('daily_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accumulated_monthly_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfitEase.product')),
            ],
        ),
    ]
